# Generated by Django 3.1.3 on 2020-11-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=True)),
                ('name', models.CharField(max_length=200)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remain_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=True)),
                ('name', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
