# Generated by Django 3.1.3 on 2020-12-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core_api', '0003_account_fk_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
