# Generated by Django 3.1.3 on 2020-12-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core_api', '0005_auto_20201212_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('date_of_execution', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('fk_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance_core_api.account')),
            ],
        ),
    ]
