# Generated by Django 3.1.3 on 2020-12-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance_core_api', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fk_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance_core_api.account'),
        ),
    ]
